DROP TABLE IF EXISTS tasks;
CREATE TABLE tasks (
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    title VARCHAR(120) NOT NULL,
    description VARCHAR(7000) NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);